package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2018_1.*
import jetbrains.buildServer.configs.kotlin.v2018_1.buildSteps.GradleBuildStep
import jetbrains.buildServer.configs.kotlin.v2018_1.buildSteps.gradle
import jetbrains.buildServer.configs.kotlin.v2018_1.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Backend_Build'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Backend_Build")) {
    check(paused == false) {
        "Unexpected paused: '$paused'"
    }
    paused = true

    expectSteps {
        gradle {
            tasks = "clean :backend:build"
            dockerImage = "openjdk:8u131-jdk-alpine"
            dockerRunParameters = "-v gradle:/root/.gradle/"
        }
    }
    steps {
        update<GradleBuildStep>(0) {
            clearConditions()
            buildFile = "build.gradle"
            param("teamcity.tool.jacoco", "")
        }
    }

    requirements {
        add {
            equals("docker.server.osType", "linux")
        }
    }
}
